import { MD3DarkTheme, MD3LightTheme, type MD3Theme } from 'react-native-paper'

import { GrayRamp } from '#src/util/theme-constant'

const einkElevation = {
  dark: {
    level0: 'transparent',
    level1: GrayRamp.gray800,
    level2: GrayRamp.gray700,
    level3: GrayRamp.gray500,
    level4: 'transparent',
    level5: 'transparent',
  },
  light: {
    level0: 'transparent',
    level1: GrayRamp.gray100,
    level2: GrayRamp.gray200,
    level3: GrayRamp.gray300,
    level4: 'transparent',
    level5: 'transparent',
  },
}

export const EinkTheme: Record<'dark' | 'light', MD3Theme> = {
  dark: {
    ...MD3DarkTheme,
    colors: {
      ...MD3DarkTheme.colors,
      background: GrayRamp.black,
      elevation: einkElevation.dark,
      error: GrayRamp.white,
      errorContainer: '#3A3D42',
      inverseOnSurface: GrayRamp.gray800,
      inversePrimary: GrayRamp.black,
      inverseSurface: GrayRamp.gray100,
      onBackground: GrayRamp.white,
      onError: GrayRamp.black,
      onErrorContainer: GrayRamp.white,
      onPrimary: GrayRamp.black,
      onPrimaryContainer: GrayRamp.white,
      onSecondary: GrayRamp.black,
      onSecondaryContainer: GrayRamp.gray100,
      onSurface: GrayRamp.white,
      onSurfaceVariant: GrayRamp.gray300,
      onTertiary: GrayRamp.black,
      onTertiaryContainer: GrayRamp.gray100,
      outline: GrayRamp.gray300,
      outlineVariant: GrayRamp.gray700,
      primary: GrayRamp.white,
      primaryContainer: GrayRamp.gray700,
      secondary: GrayRamp.gray300,
      secondaryContainer: GrayRamp.gray700,
      surface: GrayRamp.black,
      surfaceVariant: GrayRamp.gray800,
      tertiary: GrayRamp.gray300,
      tertiaryContainer: GrayRamp.gray700,
    },
  },
  light: {
    ...MD3LightTheme,
    colors: {
      ...MD3LightTheme.colors,
      background: GrayRamp.white,
      elevation: einkElevation.light,
      error: GrayRamp.black,
      errorContainer: '#D6D7DB',
      inverseOnSurface: GrayRamp.gray100,
      inversePrimary: GrayRamp.white,
      inverseSurface: GrayRamp.gray800,
      onBackground: GrayRamp.black,
      onError: GrayRamp.white,
      onErrorContainer: GrayRamp.black,
      onPrimary: GrayRamp.white,
      onPrimaryContainer: GrayRamp.black,
      onSecondary: GrayRamp.white,
      onSecondaryContainer: GrayRamp.gray800,
      onSurface: GrayRamp.black,
      onSurfaceVariant: GrayRamp.gray500,
      onTertiary: GrayRamp.white,
      onTertiaryContainer: GrayRamp.gray800,
      outline: GrayRamp.gray500,
      outlineVariant: GrayRamp.gray200,
      primary: GrayRamp.black,
      primaryContainer: GrayRamp.gray200,
      secondary: GrayRamp.gray500,
      secondaryContainer: GrayRamp.gray200,
      surface: GrayRamp.white,
      surfaceVariant: GrayRamp.gray100,
      tertiary: GrayRamp.gray500,
      tertiaryContainer: GrayRamp.gray200,
    },
  },
}
