import { MD3DarkTheme, MD3LightTheme, type MD3Theme } from 'react-native-paper'

import { BlueRamp, GrayRamp } from '#src/util/theme-constant'

export const PaperTheme: Record<'dark' | 'light', MD3Theme> = {
  dark: {
    ...MD3DarkTheme,
    colors: {
      ...MD3DarkTheme.colors,
      background: GrayRamp.black,
      error: '#FFB4AB',
      errorContainer: '#93000A',
      inverseOnSurface: GrayRamp.gray800,
      inversePrimary: BlueRamp.blue700,
      inverseSurface: GrayRamp.gray100,
      onBackground: GrayRamp.white,
      onError: '#690005',
      onErrorContainer: '#FFDAD6',
      onPrimary: BlueRamp.blue900,
      onPrimaryContainer: BlueRamp.blue100,
      onSecondary: '#141B2C',
      onSecondaryContainer: GrayRamp.gray200,
      onSurface: GrayRamp.white,
      onSurfaceVariant: GrayRamp.gray300,
      onTertiary: '#141B2C',
      onTertiaryContainer: GrayRamp.gray200,
      outline: GrayRamp.gray300,
      outlineVariant: GrayRamp.gray700,
      primary: BlueRamp.blue300,
      primaryContainer: BlueRamp.blue950,
      secondary: '#A9B2C7',
      secondaryContainer: GrayRamp.gray700,
      surface: GrayRamp.black,
      surfaceVariant: GrayRamp.gray800,
      tertiary: '#A9B2C7',
      tertiaryContainer: GrayRamp.gray700,
    },
  },
  light: {
    ...MD3LightTheme,
    colors: {
      ...MD3LightTheme.colors,
      background: GrayRamp.white,
      error: '#BA1A1A',
      errorContainer: '#FFDAD6',
      inverseOnSurface: GrayRamp.gray100,
      inversePrimary: BlueRamp.blue300,
      inverseSurface: GrayRamp.gray700,
      onBackground: GrayRamp.black,
      onError: GrayRamp.white,
      onErrorContainer: '#410002',
      onPrimary: GrayRamp.white,
      onPrimaryContainer: BlueRamp.blue900,
      onSecondary: GrayRamp.white,
      onSecondaryContainer: '#141B2C',
      onSurface: GrayRamp.black,
      onSurfaceVariant: GrayRamp.gray500,
      onTertiary: GrayRamp.white,
      onTertiaryContainer: '#141B2C',
      outline: GrayRamp.gray500,
      outlineVariant: GrayRamp.gray200,
      primary: BlueRamp.blue700,
      primaryContainer: BlueRamp.blue100,
      secondary: '#575E71',
      secondaryContainer: GrayRamp.gray200,
      surface: GrayRamp.white,
      surfaceVariant: GrayRamp.gray100,
      tertiary: '#575E71',
      tertiaryContainer: GrayRamp.gray200,
    },
  },
}
